import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LanguageSwitcher from "@/src/components/languageSwitcher";
import I18nProvider from "../components/I18nProvider";

// Fuente local OTF
const subjectivity = localFont({
  src: "./fonts/Subjectivity-Regular.otf",
  variable: "--font-subjectivity",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Cliltutors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${subjectivity.variable} antialiased`}>
        <I18nProvider>
          {children}
          <LanguageSwitcher />
        </I18nProvider>
      </body>
    </html>
  );
}
